# basic config
suffix: Default
device: 0
dataset: cifar10
model: cnncifar

# federated config
total_num: 100
sr: 0.1
rnd: 300
test_gap: 1

# local training config
bs: 64
epoch: 5
lr: 0.1
gamma: 0.99

